<?php
$screeningLabels = ['passed' => 'Lolos', 'failed' => 'Tidak lolos', 'pending' => 'Belum dinilai'];
$query = array_filter($filters, static fn ($value): bool => $value !== '' && $value !== 0);
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#102a43"><title>Laporan Pelamar | HRD Manna Kampus</title><link rel="icon" href="<?= base_url('favicon.ico') ?>"><link rel="stylesheet" href="<?= base_url('assets/css/admin-hrd.css') ?>?v=25"></head>
<body class="admin-dashboard-page"><div class="dashboard-shell">
<?= view('admin/partials/sidebar', ['auth' => $auth, 'activeMenu' => 'reports']) ?>
<main class="admin-main"><header class="admin-topbar"><button class="sidebar-toggle" type="button" aria-controls="admin-sidebar" aria-expanded="false" aria-label="Buka navigasi"><span></span><span></span><span></span></button><div><span>Recruitment Analytics</span><strong>Laporan Pelamar</strong></div><a class="view-career-link" href="<?= site_url('lowongan') ?>" target="_blank" rel="noopener">Lihat halaman karier</a></header>
<div class="admin-content report-content"><section class="dashboard-welcome department-heading"><div><span class="login-eyebrow">Applicant Report</span><h1>Pelamar yang Sudah Mendaftar</h1><p>Pantau seluruh lamaran berdasarkan posisi, departemen, status, dan periode pendaftaran.</p></div><a class="new-user-jump report-export-link" href="<?= esc(site_url('adminhrdmannakampus/laporan-pelamar/export') . ($query === [] ? '' : '?' . http_build_query($query)), 'attr') ?>">Unduh Excel</a></section>
<section class="access-summary department-summary report-summary"><article><i class="summary-card-icon icon-blue" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0M16 8h5M18.5 5.5v5"/></svg></i><strong><?= (int) $summary['applicants'] ?></strong><span>Pelamar unik</span></article><article><i class="summary-card-icon icon-purple" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 4h9l3 3v13H6V4Z"/><path d="M14 4v4h4M9 12h6M9 16h6"/></svg></i><strong><?= (int) $summary['applications'] ?></strong><span>Total lamaran</span></article><article><i class="summary-card-icon icon-green" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></svg></i><strong><?= (int) $summary['passed'] ?></strong><span>Lolos screening</span></article><article><i class="summary-card-icon icon-red" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m9 9 6 6m0-6-6 6"/></svg></i><strong><?= (int) $summary['failed'] ?></strong><span>Tidak lolos</span></article></section>
<section class="settings-card department-toolbar-card"><form class="report-filter-form" action="<?= site_url('adminhrdmannakampus/laporan-pelamar') ?>" method="get"><input type="search" name="keyword" value="<?= esc($filters['keyword'], 'attr') ?>" placeholder="Cari nama, email, WA, atau nomor"><select name="vacancy_id"><option value="">Semua posisi</option><?php foreach ($vacancies as $vacancy): ?><option value="<?= (int) $vacancy['id'] ?>" <?= $filters['vacancy_id'] === (int) $vacancy['id'] ? 'selected' : '' ?>><?= esc($vacancy['title']) ?></option><?php endforeach ?></select><select name="vacancy_period_id"><option value="">Semua sesi</option><?php foreach ($periods as $period): ?><option value="<?= (int) $period['id'] ?>" <?= $filters['vacancy_period_id'] === (int) $period['id'] ? 'selected' : '' ?>><?= esc($period['vacancy_title'] . ' — ' . $period['period_name']) ?></option><?php endforeach ?></select><select name="department_id"><option value="">Semua departemen</option><?php foreach ($departments as $department): ?><option value="<?= (int) $department['id'] ?>" <?= $filters['department_id'] === (int) $department['id'] ? 'selected' : '' ?>><?= esc($department['name']) ?></option><?php endforeach ?></select><select name="status"><option value="">Semua status</option><?php foreach ($statusLabels as $value => $label): ?><option value="<?= esc($value, 'attr') ?>" <?= $filters['status'] === $value ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select><label><span>Dari</span><input type="date" name="date_from" value="<?= esc($filters['date_from'], 'attr') ?>"></label><label><span>Sampai</span><input type="date" name="date_to" value="<?= esc($filters['date_to'], 'attr') ?>"></label><button type="submit">Terapkan</button><a href="<?= site_url('adminhrdmannakampus/laporan-pelamar') ?>">Reset</a></form></section>
<section class="settings-card report-table-card"><div class="settings-card-heading settings-heading-action"><span class="settings-icon settings-icon-green"><svg viewBox="0 0 24 24"><path d="M5 6h14M5 12h14M5 18h14"/></svg></span><div><h2>Daftar lamaran</h2><p>Satu pelamar dapat muncul beberapa kali apabila mendaftar ke lebih dari satu posisi.</p></div><span class="device-count"><?= count($applications) ?></span></div><div class="department-table-wrap"><table class="department-table report-table"><thead><tr><th class="report-order">No.</th><th>Pelamar</th><th>Posisi</th><th>Tanggal daftar</th><th>Screening</th><th>Status lamaran</th><th>Aksi</th></tr></thead><tbody>
<?php if ($applications === []): ?><tr><td colspan="7" class="department-empty">Belum ada lamaran yang sesuai dengan filter.</td></tr><?php endif ?>
<?php foreach ($applications as $index => $application): $screening = (string) ($application['screening_status'] ?: 'pending'); ?><tr><td class="report-order"><?= $index + 1 ?></td><td><div class="report-applicant"><strong><?= esc($application['full_name']) ?></strong><a href="mailto:<?= esc($application['email'], 'attr') ?>"><?= esc($application['email']) ?></a><small><?= esc($application['phone'] ?: '-') ?></small></div></td><td><div class="department-name-cell"><strong><?= esc($application['vacancy_title']) ?></strong><code><?= esc($application['period_name'] . ' · ' . $application['department_name']) ?></code></div></td><td class="report-date"><?= esc(date('d/m/Y', strtotime($application['submitted_at']))) ?><small><?= esc(date('H:i', strtotime($application['submitted_at']))) ?></small></td><td><span class="report-screening screening-<?= esc($screening, 'attr') ?>"><?= esc($screeningLabels[$screening] ?? 'Belum dinilai') ?></span><small class="report-score"><?= $application['screening_score'] === null ? '-' : esc(number_format((float) $application['screening_score'], 2, ',', '.')) ?></small></td><td><span class="report-application-status"><?= esc($application['status_label']) ?></span></td><td><?php if ($canViewCandidate): ?><a class="report-detail-link" href="<?= site_url('adminhrdmannakampus/pelamar/' . $application['applicant_id']) ?>">Detail</a><?php else: ?>-<?php endif ?></td></tr><?php endforeach ?>
</tbody></table></div></section></div></main></div><script src="<?= base_url('assets/js/admin-hrd.js') ?>?v=2" defer></script></body></html>
