<?php
$statusLabels = ['draft' => 'Draft', 'open' => 'Dibuka', 'closed' => 'Ditutup', 'archived' => 'Diarsipkan'];
$statusCounts = array_count_values(array_column($vacancies, 'status'));
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#102a43"><title>Lowongan Kerja | HRD Manna Kampus</title><link rel="icon" href="<?= base_url('favicon.ico?v=2') ?>"><link rel="stylesheet" href="<?= base_url('assets/vendor/sweetalert2/sweetalert2.min.css') ?>?v=11.26.25"><link rel="stylesheet" href="<?= base_url('assets/css/admin-hrd.css') ?>?v=66"></head>
<body class="admin-dashboard-page"><div class="dashboard-shell">
<?= view('admin/partials/sidebar', ['auth' => $auth, 'activeMenu' => 'vacancies']) ?>
<main class="admin-main"><header class="admin-topbar"><button class="sidebar-toggle" type="button" aria-controls="admin-sidebar" aria-expanded="false" aria-label="Buka navigasi"><span></span><span></span><span></span></button><div><span>Recruitment</span><strong>Lowongan Kerja</strong></div><a class="view-career-link" href="<?= site_url('lowongan') ?>" target="_blank" rel="noopener">Lihat halaman karier</a></header>
<div class="admin-content vacancy-content"><?php if ($success): ?><div class="admin-alert admin-alert-success dashboard-alert" data-swal-toast="success"><?= esc($success) ?></div><?php endif ?><?php if ($error): ?><div class="admin-alert admin-alert-error dashboard-alert" data-swal-toast="error"><?= esc($error) ?></div><?php endif ?>
<section class="dashboard-welcome department-heading"><div><span class="login-eyebrow">Vacancy Management</span><h1>Lowongan Kerja</h1><p>Kelola publikasi lowongan, kebutuhan karyawan, dan pertanyaan screening.</p></div><?php if ($canCreate): ?><a class="new-user-jump vacancy-create-link" href="<?= site_url('adminhrdmannakampus/lowongan/baru') ?>">+ Tambah lowongan</a><?php endif ?></section>
<section class="access-summary vacancy-summary"><article><i class="summary-card-icon icon-blue" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="4" y="7" width="16" height="12" rx="2"/><path d="M9 7V5h6v2M4 12h16"/></svg></i><strong><?= count($vacancies) ?></strong><span>Hasil ditampilkan</span></article><article><i class="summary-card-icon icon-green" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="4" y="7" width="16" height="12" rx="2"/><path d="M9 7V5h6v2m0 7 2 2 4-5"/></svg></i><strong><?= (int) ($statusCounts['open'] ?? 0) ?></strong><span>Sedang dibuka</span></article><article><i class="summary-card-icon icon-orange" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 4h9l3 3v13H6V4Z"/><path d="M14 4v4h4M9 12h6M9 16h4"/></svg></i><strong><?= (int) ($statusCounts['draft'] ?? 0) ?></strong><span>Draft</span></article><article><i class="summary-card-icon icon-purple" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0M16 8h5M18.5 5.5v5"/></svg></i><strong><?= array_sum(array_map('intval', array_column($vacancies, 'application_count'))) ?></strong><span>Total lamaran</span></article></section>
<section class="settings-card department-toolbar-card"><form class="vacancy-filter-form" action="<?= site_url('adminhrdmannakampus/lowongan') ?>" method="get"><input type="search" name="keyword" value="<?= esc($keyword, 'attr') ?>" placeholder="Cari posisi, kode, atau lokasi"><select name="department_id"><option value="">Semua departemen</option><?php foreach ($departments as $department): ?><option value="<?= (int) $department['id'] ?>" <?= $selectedDepartmentId === (int) $department['id'] ? 'selected' : '' ?>><?= esc($department['name']) ?></option><?php endforeach ?></select><select name="status"><option value="">Semua status</option><?php foreach ($statusLabels as $value => $label): ?><option value="<?= $value ?>" <?= $selectedStatus === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select><button type="submit">Filter</button><a href="<?= site_url('adminhrdmannakampus/lowongan') ?>">Reset</a></form></section>
<section class="settings-card vacancy-table-card"><div class="settings-card-heading settings-heading-action"><span class="settings-icon settings-icon-green"><svg viewBox="0 0 24 24"><path d="M5 6h14M5 12h14M5 18h14"/></svg></span><div><h2>Daftar lowongan</h2><p>Lowongan yang dibuka dan sesuai jadwal akan tampil pada halaman karier.</p></div><span class="device-count"><?= count($vacancies) ?></span></div><div class="department-table-wrap"><table class="department-table vacancy-table"><thead><tr><th>No.</th><th>Posisi</th><th>Departemen</th><th>Lokasi &amp; tipe</th><th>Kebutuhan</th><th>Pelamar</th><th>Periode</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php if ($vacancies === []): ?><tr><td colspan="9" class="department-empty">Lowongan tidak ditemukan.</td></tr><?php endif ?><?php foreach ($vacancies as $vacancyIndex => $vacancy): ?><tr><td><?= $vacancyIndex + 1 ?></td><td><div class="department-name-cell"><strong><?= esc($vacancy['title']) ?></strong><code><?= esc($vacancy['code']) ?></code></div></td><td><?= esc($vacancy['department_name']) ?></td><td><strong><?= esc($vacancy['location'] ?: '-') ?></strong><small class="vacancy-table-subtext"><?= esc($vacancy['employment_type'] ?: '-') ?></small></td><td><?= (int) $vacancy['headcount'] ?> orang</td><td><span class="department-vacancy-count"><?= (int) $vacancy['application_count'] ?> pelamar</span></td><td class="vacancy-period"><?= $vacancy['opened_at'] ? esc(date('d/m/Y', strtotime($vacancy['opened_at']))) : '-' ?><small>s.d. <?= $vacancy['closed_at'] ? esc(date('d/m/Y', strtotime($vacancy['closed_at']))) : 'tanpa batas' ?></small></td><td><span class="vacancy-status status-<?= esc($vacancy['status'], 'attr') ?>"><?= esc($statusLabels[$vacancy['status']] ?? $vacancy['status']) ?></span></td><td><div class="vacancy-actions"><?php if ($canUpdate): ?><a class="table-action-icon table-action-edit" href="<?= site_url('adminhrdmannakampus/lowongan/' . $vacancy['id'] . '/edit') ?>" aria-label="Edit lowongan" title="Edit lowongan"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20h4L19 9l-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/></svg></a><?php endif ?><?php if ($canViewVacancyPeriods): ?><a href="<?= site_url('adminhrdmannakampus/sesi-lowongan?vacancy_id=' . $vacancy['id']) ?>">Sesi</a><?php endif ?><?php if ($canDelete): ?><form action="<?= site_url('adminhrdmannakampus/lowongan/' . $vacancy['id'] . '/hapus') ?>" method="post" data-confirm="Hapus lowongan ini?"><?= csrf_field() ?><button class="department-delete-button table-action-icon table-action-delete" type="submit" aria-label="Hapus lowongan" <?= (int) $vacancy['application_count'] > 0 ? 'disabled title="Sudah memiliki pelamar"' : 'title="Hapus lowongan"' ?>><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg></button></form><?php endif ?><?php if (! $canUpdate && ! $canViewVacancyPeriods && ! $canDelete): ?><span class="protected-label">Lihat saja</span><?php endif ?></div></td></tr><?php endforeach ?>
</tbody></table></div></section></div><?= view('admin/partials/footer') ?>
    </main></div><script src="<?= base_url('assets/vendor/sweetalert2/sweetalert2.all.min.js') ?>?v=11.26.25" defer></script><script src="<?= base_url('assets/js/admin-hrd.js') ?>?v=7" defer></script></body></html>
