<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->set404Override('\\App\\Controllers\\NotFound::index');

$routes->get('/', 'Home::index');
$routes->get('lowongan', '\App\Modules\Recruitment\Controllers\VacancyController::index');
$routes->get('lowongan/cari', '\App\Modules\Recruitment\Controllers\VacancyController::search');
$routes->get('lowongan/(:segment)/lamar', '\App\Modules\Recruitment\Controllers\ApplicationController::create/$1');
$routes->post('lowongan/(:segment)/lamar', '\App\Modules\Recruitment\Controllers\ApplicationController::store/$1');
$routes->get('lamaran/csrf', '\App\Modules\Recruitment\Controllers\ApplicationController::csrf');
$routes->get('lamaran/berhasil', '\App\Modules\Recruitment\Controllers\ApplicationController::success');
$routes->get('lamaran/tidak-dapat-diproses', '\App\Modules\Recruitment\Controllers\ApplicationController::restricted');
$routes->get('lamaran/bukti/(:segment)', '\App\Modules\Recruitment\Controllers\ApplicationController::receipt/$1');
$routes->get('lamaran/status', '\App\Modules\Recruitment\Controllers\ApplicationStatusController::index');
$routes->post('lamaran/status', '\App\Modules\Recruitment\Controllers\ApplicationStatusController::lookup');
$routes->post('lamaran/status/jadwal/(:num)', '\App\Modules\Recruitment\Controllers\ApplicationStatusController::respond/$1');
$routes->get('tahapan-seleksi', 'Home::selectionProcess');

$routes->group('api/storage', [
    'namespace' => 'App\Modules\Recruitment\Controllers',
    'filter' => 'storage-sync',
], static function (RouteCollection $routes): void {
    $routes->get('documents/pending', 'StorageSyncController::pending');
    $routes->get('documents/(:num)/download', 'StorageSyncController::download/$1');
    $routes->post('documents/(:num)/confirm', 'StorageSyncController::confirm/$1');
});

$routes->group('adminhrdmannakampus', ['namespace' => 'App\Modules\Admin\Controllers'], static function ($routes): void {
    $routes->get('', 'AuthController::login', ['as' => 'hrd.login']);
    $routes->post('', 'AuthController::authenticate', ['as' => 'hrd.authenticate']);
    $routes->get('dashboard', 'DashboardController::index', ['filter' => 'permission:dashboard.admin.view', 'as' => 'hrd.dashboard']);
    $routes->get('kalender-rekrutmen', 'RecruitmentCalendarController::index', ['filter' => 'permission:schedules.view', 'as' => 'hrd.recruitment.calendar']);
    $routes->get('rekap-kehadiran', 'AttendanceRecapController::index', ['filter' => 'permission:schedules.view', 'as' => 'hrd.attendance.recap']);
    $routes->get('rekap-kehadiran/export', 'AttendanceRecapController::export', ['filter' => 'permission:schedules.view', 'as' => 'hrd.attendance.recap.export']);
    $routes->get('profil', 'ProfileController::index', ['filter' => 'hrd-auth', 'as' => 'hrd.profile']);
    $routes->post('profil', 'ProfileController::update', ['filter' => 'hrd-auth', 'as' => 'hrd.profile.update']);
    $routes->post('profil/password', 'ProfileController::updatePassword', ['filter' => 'hrd-auth', 'as' => 'hrd.profile.password']);
    $routes->post('profil/perangkat/(:num)/revoke', 'ProfileController::revokeSession/$1', ['filter' => 'hrd-auth', 'as' => 'hrd.profile.session.revoke']);
    $routes->post('profil/perangkat/revoke-all', 'ProfileController::revokeAllSessions', ['filter' => 'hrd-auth', 'as' => 'hrd.profile.sessions.revoke']);
    $routes->get('akses', 'AccessController::index', ['filter' => 'super-admin', 'as' => 'hrd.access']);
    $routes->get('history-log', 'HistoryLogController::index', ['filter' => 'super-admin', 'as' => 'hrd.history.logs']);
    $routes->post('akses/users', 'AccessController::createUser', ['filter' => 'super-admin', 'as' => 'hrd.access.users.create']);
    $routes->post('akses/users/(:num)/status', 'AccessController::updateStatus/$1', ['filter' => 'super-admin', 'as' => 'hrd.access.users.status']);
    $routes->post('akses/users/(:num)/role', 'AccessController::updateRole/$1', ['filter' => 'super-admin', 'as' => 'hrd.access.users.role']);
    $routes->post('akses/roles/(:num)/permissions', 'AccessController::updatePermissions/$1', ['filter' => 'super-admin', 'as' => 'hrd.access.permissions']);
    $routes->get('departemen', 'DepartmentController::index', ['filter' => 'permission:departments.view', 'as' => 'hrd.departments']);
    $routes->post('departemen', 'DepartmentController::create', ['filter' => 'permission:departments.manage', 'as' => 'hrd.departments.create']);
    $routes->post('departemen/(:num)', 'DepartmentController::update/$1', ['filter' => 'permission:departments.manage', 'as' => 'hrd.departments.update']);
    $routes->post('departemen/(:num)/status', 'DepartmentController::toggle/$1', ['filter' => 'permission:departments.manage', 'as' => 'hrd.departments.status']);
    $routes->post('departemen/(:num)/hapus', 'DepartmentController::delete/$1', ['filter' => 'permission:departments.delete', 'as' => 'hrd.departments.delete']);
    $routes->get('lowongan', 'VacancyManagementController::index', ['filter' => 'permission:vacancies.view', 'as' => 'hrd.vacancies']);
    $routes->get('lowongan/baru', 'VacancyManagementController::create', ['filter' => 'permission:vacancies.create', 'as' => 'hrd.vacancies.create']);
    $routes->post('lowongan', 'VacancyManagementController::store', ['filter' => 'permission:vacancies.create', 'as' => 'hrd.vacancies.store']);
    $routes->get('lowongan/(:num)/edit', 'VacancyManagementController::edit/$1', ['filter' => 'permission:vacancies.update', 'as' => 'hrd.vacancies.edit']);
    $routes->post('lowongan/(:num)', 'VacancyManagementController::update/$1', ['filter' => 'permission:vacancies.update', 'as' => 'hrd.vacancies.update']);
    $routes->post('lowongan/(:num)/status', 'VacancyManagementController::changeStatus/$1', ['filter' => 'permission:vacancies.publish', 'as' => 'hrd.vacancies.status']);
    $routes->post('lowongan/(:num)/hapus', 'VacancyManagementController::delete/$1', ['filter' => 'permission:vacancies.delete', 'as' => 'hrd.vacancies.delete']);
    $routes->get('sesi-lowongan', 'VacancyPeriodController::index', ['filter' => 'permission:vacancy.periods.view', 'as' => 'hrd.vacancy.periods']);
    $routes->post('sesi-lowongan', 'VacancyPeriodController::create', ['filter' => 'permission:vacancy.periods.manage', 'as' => 'hrd.vacancy.periods.create']);
    $routes->post('sesi-lowongan/(:num)', 'VacancyPeriodController::update/$1', ['filter' => 'permission:vacancy.periods.manage', 'as' => 'hrd.vacancy.periods.update']);
    $routes->post('sesi-lowongan/(:num)/status', 'VacancyPeriodController::changeStatus/$1', ['filter' => 'permission:vacancy.periods.publish', 'as' => 'hrd.vacancy.periods.status']);
    $routes->post('sesi-lowongan/(:num)/hapus', 'VacancyPeriodController::delete/$1', ['filter' => 'permission:vacancy.periods.manage', 'as' => 'hrd.vacancy.periods.delete']);
    $routes->get('template-tahapan', 'RecruitmentProcessTemplateController::index', ['filter' => 'permission:recruitment.templates.view', 'as' => 'hrd.recruitment.templates']);
    $routes->post('template-tahapan', 'RecruitmentProcessTemplateController::create', ['filter' => 'permission:recruitment.templates.manage', 'as' => 'hrd.recruitment.templates.create']);
    $routes->post('template-tahapan/(:num)', 'RecruitmentProcessTemplateController::update/$1', ['filter' => 'permission:recruitment.templates.manage', 'as' => 'hrd.recruitment.templates.update']);
    $routes->post('template-tahapan/(:num)/hapus', 'RecruitmentProcessTemplateController::delete/$1', ['filter' => 'permission:recruitment.templates.manage', 'as' => 'hrd.recruitment.templates.delete']);
    $routes->post('template-tahapan/jenis', 'RecruitmentProcessTemplateController::createStage', ['filter' => 'permission:recruitment.templates.manage', 'as' => 'hrd.recruitment.stage-types.create']);
    $routes->post('template-tahapan/jenis/(:num)', 'RecruitmentProcessTemplateController::updateStage/$1', ['filter' => 'permission:recruitment.templates.manage', 'as' => 'hrd.recruitment.stage-types.update']);
    $routes->post('template-tahapan/jenis/(:num)/hapus', 'RecruitmentProcessTemplateController::deleteStage/$1', ['filter' => 'permission:recruitment.templates.manage', 'as' => 'hrd.recruitment.stage-types.delete']);
    $routes->get('pertanyaan-screening', 'ScreeningQuestionController::index', ['filter' => 'permission:screening.questions.view', 'as' => 'hrd.screening.questions']);
    $routes->post('pertanyaan-screening/default', 'ScreeningQuestionController::createDefault', ['filter' => 'permission:screening.defaults.manage', 'as' => 'hrd.screening.defaults.create']);
    $routes->post('pertanyaan-screening/default/(:num)', 'ScreeningQuestionController::updateDefault/$1', ['filter' => 'permission:screening.defaults.manage', 'as' => 'hrd.screening.defaults.update']);
    $routes->post('pertanyaan-screening/default/(:num)/hapus', 'ScreeningQuestionController::deleteDefault/$1', ['filter' => 'permission:screening.defaults.manage', 'as' => 'hrd.screening.defaults.delete']);
    $routes->post('pertanyaan-screening/lowongan/(:num)/salin-default', 'ScreeningQuestionController::copyDefaults/$1', ['filter' => 'permission:screening.vacancies.manage', 'as' => 'hrd.screening.vacancies.copy']);
    $routes->post('pertanyaan-screening/lowongan/(:num)', 'ScreeningQuestionController::createVacancyQuestion/$1', ['filter' => 'permission:screening.vacancies.manage', 'as' => 'hrd.screening.vacancies.create']);
    $routes->post('pertanyaan-screening/lowongan/(:num)/(:num)', 'ScreeningQuestionController::updateVacancyQuestion/$1/$2', ['filter' => 'permission:screening.vacancies.manage', 'as' => 'hrd.screening.vacancies.update']);
    $routes->post('pertanyaan-screening/lowongan/(:num)/(:num)/hapus', 'ScreeningQuestionController::deleteVacancyQuestion/$1/$2', ['filter' => 'permission:screening.vacancies.manage', 'as' => 'hrd.screening.vacancies.delete']);
    $routes->get('list-pelamar', 'ApplicantReportController::index', ['filter' => 'permission:applicants.pool.view', 'as' => 'hrd.applicant.pool']);
    $routes->post('list-pelamar/(:num)/pilih', 'ApplicantReportController::assign/$1', ['filter' => 'permission:applicants.assign', 'as' => 'hrd.applicant.assign']);
    $routes->get('list-pelamar/export', 'ApplicantReportController::export', ['filter' => 'permission:applicants.pool.view', 'as' => 'hrd.applicant.pool.export']);
    $routes->get('laporan-pelamar', 'ApplicantReportController::index', ['filter' => 'permission:applicants.pool.view']);
    $routes->get('laporan-pelamar/export', 'ApplicantReportController::export', ['filter' => 'permission:applicants.pool.view']);
    $routes->get('pelamar/(:num)', 'ApplicantDetailController::show/$1', ['filter' => 'permission:candidates.view', 'as' => 'hrd.applicant.detail']);
    $routes->get('pelamar/(:num)/scorecard.pdf', 'ApplicantScorecardController::download/$1', ['filter' => 'permission:candidates.view', 'as' => 'hrd.applicant.scorecard']);
    $routes->post('pelamar/(:num)/penilaian', 'ApplicantRecommendationController::save/$1', ['filter' => 'permission:recommendations.manage', 'as' => 'hrd.applicant.recommendation.save']);
    $routes->get('pelamar/(:num)/dokumen/(:num)', 'ApplicantDetailController::downloadDocument/$1/$2', ['filter' => 'permission:candidates.cv.download', 'as' => 'hrd.applicant.document']);
    $routes->get('blacklist-pelamar', 'ApplicantBlacklistController::index', ['filter' => 'permission:applicants.blacklist.view', 'as' => 'hrd.applicant.blacklist']);
    $routes->post('blacklist-pelamar/pelamar/(:num)', 'ApplicantBlacklistController::create/$1', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.applicant.blacklist.create']);
    $routes->post('blacklist-pelamar/(:num)', 'ApplicantBlacklistController::update/$1', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.applicant.blacklist.update']);
    $routes->post('blacklist-pelamar/(:num)/cabut', 'ApplicantBlacklistController::revoke/$1', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.applicant.blacklist.revoke']);
    $routes->get('blacklist-historis', 'HistoricalBlacklistController::index', ['filter' => 'permission:applicants.blacklist.view', 'as' => 'hrd.historical.blacklist']);
    $routes->get('blacklist-historis/template', 'HistoricalBlacklistController::template', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.historical.blacklist.template']);
    $routes->post('blacklist-historis/import', 'HistoricalBlacklistController::import', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.historical.blacklist.import']);
    $routes->post('blacklist-historis', 'HistoricalBlacklistController::create', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.historical.blacklist.create']);
    $routes->post('blacklist-historis/(:num)', 'HistoricalBlacklistController::update/$1', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.historical.blacklist.update']);
    $routes->post('blacklist-historis/(:num)/cabut', 'HistoricalBlacklistController::revoke/$1', ['filter' => 'permission:applicants.blacklist.manage', 'as' => 'hrd.historical.blacklist.revoke']);
    $routes->get('kandidat', 'CandidateController::index', ['filter' => 'permission:candidates.view', 'as' => 'hrd.candidates']);
    $routes->get('kandidat/export', 'CandidateController::export', ['filter' => 'permission:candidates.view', 'as' => 'hrd.candidates.export']);
    $routes->post('kandidat/pelamar/(:num)/batal-pilih', 'CandidateController::cancelAssignment/$1', ['filter' => 'permission:applicants.assign', 'as' => 'hrd.candidates.assignment.cancel']);
    $routes->post('kandidat/lamaran/(:num)/tahap', 'CandidateController::updateStage/$1', ['filter' => 'permission:candidates.status.update', 'as' => 'hrd.candidates.stage']);
    $routes->post('kandidat/lamaran/(:num)/urungkan-tahap', 'CandidateController::undoStage/$1', ['filter' => 'permission:candidates.status.update', 'as' => 'hrd.candidates.stage.undo']);
    $routes->post('jadwal/(:num)', 'ScheduleController::update/$1', ['filter' => 'permission:schedules.manage', 'as' => 'hrd.schedules.update']);
    $routes->post('jadwal/(:num)/jadwal-ulang', 'ScheduleController::rescheduleAfterAbsence/$1', ['filter' => 'permission:schedules.manage', 'as' => 'hrd.schedules.reschedule']);
    $routes->post('jadwal/(:num)/batal', 'ScheduleController::cancel/$1', ['filter' => 'permission:schedules.manage', 'as' => 'hrd.schedules.cancel']);
    $routes->post('jadwal/(:num)/kehadiran', 'ScheduleController::attendance/$1', ['filter' => 'permission:schedules.attendance', 'as' => 'hrd.schedules.attendance']);
    $routes->get('talent-pool', 'TalentPoolController::index', ['filter' => 'permission:candidates.view', 'as' => 'hrd.talent.pool']);
    $routes->post('talent-pool/simpan/(:num)', 'TalentPoolController::save/$1', ['filter' => 'permission:candidates.status.update', 'as' => 'hrd.talent.pool.save']);
    $routes->post('talent-pool/(:num)', 'TalentPoolController::update/$1', ['filter' => 'permission:candidates.status.update', 'as' => 'hrd.talent.pool.update']);
    $routes->post('talent-pool/(:num)/panggil', 'TalentPoolController::contact/$1', ['filter' => 'permission:candidates.status.update', 'as' => 'hrd.talent.pool.contact']);
    $routes->get('tim-hrd', 'HrdTeamController::index', ['filter' => 'permission:hrd.teams.view', 'as' => 'hrd.teams']);
    $routes->post('tim-hrd', 'HrdTeamController::create', ['filter' => 'permission:hrd.teams.manage', 'as' => 'hrd.teams.create']);
    $routes->post('tim-hrd/(:num)', 'HrdTeamController::update/$1', ['filter' => 'permission:hrd.teams.manage', 'as' => 'hrd.teams.update']);
    $routes->post('tim-hrd/user/(:num)', 'HrdTeamController::assignUser/$1', ['filter' => 'permission:hrd.teams.manage', 'as' => 'hrd.teams.users.assign']);
    $routes->get('pengaturan-rekrutmen', 'RecruitmentSettingsController::index', ['filter' => 'permission:recruitment.settings.view', 'as' => 'hrd.recruitment.settings']);
    $routes->post('pengaturan-rekrutmen/penolakan', 'RecruitmentSettingsController::createRejectionTemplate', ['filter' => 'permission:recruitment.settings.manage', 'as' => 'hrd.recruitment.rejections.create']);
    $routes->post('pengaturan-rekrutmen/penolakan/(:num)', 'RecruitmentSettingsController::updateRejectionTemplate/$1', ['filter' => 'permission:recruitment.settings.manage', 'as' => 'hrd.recruitment.rejections.update']);
    $routes->post('pengaturan-rekrutmen/penolakan/(:num)/status', 'RecruitmentSettingsController::toggleRejectionTemplate/$1', ['filter' => 'permission:recruitment.settings.manage', 'as' => 'hrd.recruitment.rejections.status']);
    $routes->post('pengaturan-rekrutmen/penolakan/(:num)/hapus', 'RecruitmentSettingsController::deleteRejectionTemplate/$1', ['filter' => 'permission:recruitment.settings.manage', 'as' => 'hrd.recruitment.rejections.delete']);
    $routes->get('aspek-penilaian', 'RecommendationAspectController::index', ['filter' => 'permission:recommendation.aspects.view', 'as' => 'hrd.recommendation.aspects']);
    $routes->post('aspek-penilaian', 'RecommendationAspectController::create', ['filter' => 'permission:recommendation.aspects.manage', 'as' => 'hrd.recommendation.aspects.create']);
    $routes->post('aspek-penilaian/(:num)', 'RecommendationAspectController::update/$1', ['filter' => 'permission:recommendation.aspects.manage', 'as' => 'hrd.recommendation.aspects.update']);
    $routes->post('aspek-penilaian/(:num)/status', 'RecommendationAspectController::toggle/$1', ['filter' => 'permission:recommendation.aspects.manage', 'as' => 'hrd.recommendation.aspects.status']);
    $routes->post('aspek-penilaian/(:num)/hapus', 'RecommendationAspectController::delete/$1', ['filter' => 'permission:recommendation.aspects.manage', 'as' => 'hrd.recommendation.aspects.delete']);
    $routes->get('template-whatsapp', 'WhatsappTemplateController::index', ['filter' => 'permission:whatsapp.templates.view', 'as' => 'hrd.whatsapp.templates']);
    $routes->post('template-whatsapp', 'WhatsappTemplateController::create', ['filter' => 'permission:whatsapp.templates.manage', 'as' => 'hrd.whatsapp.templates.create']);
    $routes->post('template-whatsapp/(:num)', 'WhatsappTemplateController::update/$1', ['filter' => 'permission:whatsapp.templates.manage', 'as' => 'hrd.whatsapp.templates.update']);
    $routes->post('template-whatsapp/(:num)/status', 'WhatsappTemplateController::toggle/$1', ['filter' => 'permission:whatsapp.templates.manage', 'as' => 'hrd.whatsapp.templates.status']);
    $routes->post('template-whatsapp/(:num)/hapus', 'WhatsappTemplateController::delete/$1', ['filter' => 'permission:whatsapp.templates.manage', 'as' => 'hrd.whatsapp.templates.delete']);
    $routes->post('logout', 'AuthController::logout', ['filter' => 'hrd-auth', 'as' => 'hrd.logout']);
});
