<?php $question = $question ?? []; ?>
<label class="screening-edit-question">Pertanyaan<input type="text" name="question_text" value="<?= esc((string) ($question['question_text'] ?? ''), 'attr') ?>" maxlength="500" required></label>
<label>Tipe jawaban<select name="answer_type"><?php foreach (['text' => 'Teks', 'number' => 'Angka', 'boolean' => 'Ya/Tidak (1/0)', 'yes_no' => 'Ya/Tidak', 'choice' => 'Pilihan', 'education_level' => 'Pendidikan'] as $value => $label): ?><option value="<?= esc($value, 'attr') ?>" <?= ($question['answer_type'] ?? 'text') === $value ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select><small class="screening-field-help">Menentukan bentuk jawaban yang diisi pelamar.</small></label>
<label>Operator<select name="comparison_operator"><?php foreach (['' => 'Tanpa evaluasi', 'equals' => 'Sama dengan', 'between' => 'Di antara', 'greater_than_or_equal' => 'Minimal', 'minimum_education' => 'Pendidikan minimal'] as $value => $label): ?><option value="<?= esc($value, 'attr') ?>" <?= ($question['comparison_operator'] ?? '') === $value ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select><small class="screening-field-help">Aturan untuk membandingkan jawaban dengan jawaban harapan.</small></label>
<label>Jawaban harapan<input type="text" name="expected_value" value="<?= esc((string) ($question['expected_value'] ?? ''), 'attr') ?>" maxlength="255"></label>
<label>Opsi dipisahkan koma<input type="text" name="answer_options" value="<?= esc((string) ($optionText ?? ''), 'attr') ?>"></label>
<label>Urutan<input type="number" name="display_order" value="<?= esc((string) ($question['display_order'] ?? 10), 'attr') ?>" min="0" max="999"></label>
<div class="screening-form-guide">
    <div><strong>Panduan tipe jawaban</strong><p><b>Teks</b> untuk jawaban bebas. <b>Angka</b> untuk usia atau pengalaman. <b>Ya/Tidak</b> untuk persetujuan. <b>Pilihan</b> menggunakan opsi yang dipisahkan koma. <b>Pendidikan</b> untuk membandingkan jenjang.</p></div>
    <div><strong>Panduan operator</strong><p><b>Tanpa evaluasi</b> hanya menyimpan jawaban. <b>Sama dengan</b> harus persis sesuai. <b>Di antara</b> memakai rentang seperti 18-30. <b>Minimal</b> memakai batas seperti 2. <b>Pendidikan minimal</b> memakai jenjang seperti D3.</p></div>
    <small>Operator menentukan kelayakan jawaban. Kandidat otomatis gugur hanya jika pertanyaan juga ditandai <b>Knockout</b>.</small>
</div>
<div class="screening-flags"><label><input type="checkbox" name="is_required" value="1" <?= ! array_key_exists('is_required', $question) || $question['is_required'] ? 'checked' : '' ?>> Wajib</label><label><input type="checkbox" name="is_knockout" value="1" <?= ! empty($question['is_knockout']) ? 'checked' : '' ?>> Knockout</label><label><input type="checkbox" name="is_active" value="1" <?= ! array_key_exists('is_active', $question) || $question['is_active'] ? 'checked' : '' ?>> Aktif</label></div>
